spring:
  kafka:
    bootstrap-servers: http://localhost:9092
    streams:
      replication-factor: 3
      application-id: user-app-streams
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: user-app-group
    properties:
      schema.registry.url: http://localhost:8081
